/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique identifier of an answered question in the format of UUID
 */
export type QuestionID = string;
/**
 * Yes (`true`), no (`false`) or neutral (`null`) answer to a question
 */
export type Answer1 = boolean | null;
/**
 * Whether a question was marked as important
 */
export type Answer2 = boolean;

/**
 * Answer to a question of a calculator
 */
export interface Answer {
  questionId: QuestionID;
  answer?: Answer1;
  isImportant?: Answer2;
  [k: string]: unknown;
}
