/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Human-friendly unique key of a district in the hyphen-separated lowercased format
 */
export type Key = string;
/**
 * Official district code assigned by the election authority
 */
export type Code = string;

/**
 * Geographical area of an election
 */
export interface District {
  key: Key;
  code?: Code;
  [k: string]: unknown;
}
