/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Round ordinal number from 0
 */
export type Number = number;
/**
 * One or multiple voting hours for the round
 *
 * @minItems 1
 */
export type VotingHours = [VotingPeriod, ...VotingPeriod[]];
/**
 * Start date (or time) of a voting period in the ISO 8601 format
 */
export type StartTime = string | string;
/**
 * End date (or time) of a voting period in the ISO 8601 format
 */
export type EndTime = string | string;

/**
 * Round of an election
 */
export interface Round {
  number: Number;
  votingHours?: VotingHours;
  [k: string]: unknown;
}
export interface VotingPeriod {
  start: StartTime;
  end: EndTime;
  [k: string]: unknown;
}
