/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Ordered list of tags
 *
 * @minItems 1
 */
export type Tags = [Tag, ...Tag[]];
/**
 * Tag with max. 25 characters
 */
export type Tag = string;
