/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Start date (or time) of a voting period in the ISO 8601 format
 */
export type StartTime = string;
/**
 * End date (or time) of a voting period in the ISO 8601 format
 */
export type EndTime = string;

/**
 * Time period from–to
 */
export interface TimePeriod {
  start: StartTime;
  end: EndTime;
  [k: string]: unknown;
}
