/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CandidateId = string;
export type Name = string;
export type ShortName = string;
export type Abbreviation = string;
export type Logo = string;

export interface CandidateRest {
  candidate_id: CandidateId;
  name: Name;
  short_name: ShortName;
  abbreviation: Abbreviation;
  logo: Logo;
  [k: string]: unknown;
}
