/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ResultId = string;
export type CreatedAt = string;
export type QuestionId = string;
export type Answer = string;
export type IsImportant = boolean;
export type Answers = AnswerRest[];
export type CandidateId = string;
export type Name = string;
export type ShortName = string;
export type Abbreviation = string;
export type Logo = string;
export type Score = number;
export type Matches = MatchRest[];
export type Id = string;
export type Name1 = string;
export type Description = string;
export type DistrictCode = string;
export type Id1 = string;
export type Key = string;
export type Name2 = string;
export type Description1 = string;
/**
 * An enumeration.
 */
export type ElectionTypeRest =
  | 'senatni'
  | 'prezidentske'
  | 'snemovni'
  | 'krajske'
  | 'municipalni'
  | 'undefined';
export type Source = string;

export interface ResultOutRest {
  result_id: ResultId;
  created_at: CreatedAt;
  answers: Answers;
  matches: Matches;
  calculator: CalculatorRest;
  source?: Source;
  [k: string]: unknown;
}
export interface AnswerRest {
  question_id: QuestionId;
  answer: Answer;
  is_important: IsImportant;
  [k: string]: unknown;
}
export interface MatchRest {
  candidate: CandidateRest;
  score: Score;
  [k: string]: unknown;
}
export interface CandidateRest {
  candidate_id: CandidateId;
  name: Name;
  short_name: ShortName;
  abbreviation: Abbreviation;
  logo: Logo;
  [k: string]: unknown;
}
export interface CalculatorRest {
  id: Id;
  name: Name1;
  description: Description;
  district_code: DistrictCode;
  election: ElectionRest;
  [k: string]: unknown;
}
export interface ElectionRest {
  id: Id1;
  key: Key;
  name: Name2;
  description: Description1;
  type: ElectionTypeRest;
  [k: string]: unknown;
}
