/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A representation all elections
 */
export interface Calculators {
  elections: Election[];
  calculators: {
    /**
     * UUID of election
     */
    election_id: string;
    district_code: string;
    label: string;
    description?: string;
    /**
     * Show on HP start - ISO 8601
     */
    on_hp_from?: string;
    /**
     * Show on HP end - ISO 8601
     */
    on_hp_to?: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
/**
 * A representation of election
 */
export interface Election {
  /**
   * UUID
   */
  id: string;
  /**
   * Key used in path/url
   */
  key: string;
  /**
   * Election's name
   */
  name: string;
  /**
   * Longer description
   */
  description: string;
  /**
   * Election start - ISO 8601
   */
  from?: string;
  /**
   * Election end - ISO 8601
   */
  to?: string;
  /**
   * Election type
   */
  type?: 'senatni' | 'prezidentske' | 'snemovni' | 'krajske' | 'municipalni';
  [k: string]: unknown;
}
