/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A representation of candidate
 */
export interface DeprecatedCandidate {
  /**
   * UUID
   */
  id: string;
  /**
   * Candidate's name
   */
  name: string;
  /**
   * Party short name
   */
  short_name?: string;
  /**
   * Given name if it makes sense
   */
  given_name?: string;
  /**
   * Family name if it makes sense
   */
  family_name?: string;
  /**
   * Candidate type
   */
  type: "party" | "coalition" | "person";
  /**
   * Longer description.
   */
  description: string;
  /**
   * Candidate's motto.
   */
  motto?: string;
  /**
   * Image
   */
  img_url?: string;
  /**
   * Is candidate active? This is useful for second round.
   */
  is_active?: boolean;
  contact?: DeprecatedContact;
  /**
   * If the type is party, then this array should have single element. If the type is coalition, then there should be multiple parties. If the type is party, then there should be at most one party.
   */
  parties?: DeprecatedParty[];
  [k: string]: unknown;
}
/**
 * A representation of contact
 */
export interface DeprecatedContact {
  /**
   * Websites
   */
  webs?: {
    /**
     * URL
     */
    url: string;
    /**
     * Label for the URL
     */
    label?: string;
    [k: string]: unknown;
  }[];
  /**
   * Emails
   */
  emails?: {
    /**
     * email
     */
    email: string;
    /**
     * Label for the email
     */
    label?: string;
    [k: string]: unknown;
  }[];
  /**
   * Twitter handle
   */
  twitter?: string;
  /**
   * Instagram handle
   */
  instagram?: string;
  /**
   * Facebook handle
   */
  facebook?: string;
  /**
   * Tiktok handle
   */
  tiktok?: string;
  [k: string]: unknown;
}
/**
 * A representation of party
 */
export interface DeprecatedParty {
  /**
   * UUID
   */
  id: string;
  /**
   * Party name
   */
  name: string;
  /**
   * Party short name
   */
  short_name?: string;
  /**
   * Longer description.
   */
  description: string;
  /**
   * abbreviation
   */
  abbreviation?: string;
  /**
   * Image
   */
  img_url?: string;
  contact?: Contact;
  [k: string]: unknown;
}
