/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A representation of election
 */
export interface DeprecatedElection {
  /**
   * UUID
   */
  id: string;
  /**
   * Key used in path/url
   */
  key: string;
  /**
   * Election's name
   */
  name: string;
  /**
   * Longer description
   */
  description: string;
  /**
   * Instructions for filling calculators for this election
   */
  instructions?: {
    [k: string]: unknown;
  };
  /**
   * Election start - ISO 8601
   */
  from?: string;
  /**
   * Election end - ISO 8601
   */
  to?: string;
  /**
   * Election type
   */
  type?: "senatni" | "prezidentske" | "snemovni" | "krajske" | "municipalni";
  [k: string]: unknown;
}
