/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A representation of single question
 */
export interface DeprecatedQuestion {
  /**
   * UUID
   */
  id: string;
  /**
   * UUID
   */
  name: string;
  /**
   * Text of the question
   */
  title: string;
  /**
   * Shorter explanation of the question
   */
  gist: string;
  /**
   * Longer explanation of the question
   */
  detail: string;
  /**
   * Tags for the question
   */
  tags?: string[];
  [k: string]: unknown;
}
