name: Check code quality

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pre-commit
          make install-all
      - name: Install pre-commit hooks
        run: |
          make pre-commit-install
      - name: Run pre-commit
        run: |
          make pre-commit-run-all
      - name: Run tests
        run: |
          make test
